package com.cdut.myschool.persist.entity;

public class LearnType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_type.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_type.user_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_type.name
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_type.parent
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_type.id
     *
     * @return the value of learn_type.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_type.id
     *
     * @param id the value for learn_type.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_type.user_id
     *
     * @return the value of learn_type.user_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_type.user_id
     *
     * @param userId the value for learn_type.user_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_type.name
     *
     * @return the value of learn_type.name
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_type.name
     *
     * @param name the value for learn_type.name
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_type.parent
     *
     * @return the value of learn_type.parent
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_type.parent
     *
     * @param parent the value for learn_type.parent
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }
}