package com.cdut.myschool.persist.entity;

import java.util.Date;

public class Plan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.id
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.user_id
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.plan_name
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    private String planName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.plan_type
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    private Integer planType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.time
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan.dead_time
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    private Date deadTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.id
     *
     * @return the value of plan.id
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.id
     *
     * @param id the value for plan.id
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.user_id
     *
     * @return the value of plan.user_id
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.user_id
     *
     * @param userId the value for plan.user_id
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.plan_name
     *
     * @return the value of plan.plan_name
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.plan_name
     *
     * @param planName the value for plan.plan_name
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.plan_type
     *
     * @return the value of plan.plan_type
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public Integer getPlanType() {
        return planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.plan_type
     *
     * @param planType the value for plan.plan_type
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public void setPlanType(Integer planType) {
        this.planType = planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.time
     *
     * @return the value of plan.time
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.time
     *
     * @param time the value for plan.time
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan.dead_time
     *
     * @return the value of plan.dead_time
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public Date getDeadTime() {
        return deadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan.dead_time
     *
     * @param deadTime the value for plan.dead_time
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    public void setDeadTime(Date deadTime) {
        this.deadTime = deadTime;
    }
}