package com.cdut.myschool.persist.entity;

public class RoastKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.type
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.id
     *
     * @return the value of roast.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.id
     *
     * @param id the value for roast.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.type
     *
     * @return the value of roast.type
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.type
     *
     * @param type the value for roast.type
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }
}