package com.cdut.myschool.persist.entity;

import java.util.Date;

public class Roast extends RoastKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.topic_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.context
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roast.time
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.topic_id
     *
     * @return the value of roast.topic_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.topic_id
     *
     * @param topicId the value for roast.topic_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId == null ? null : topicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.context
     *
     * @return the value of roast.context
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.context
     *
     * @param context the value for roast.context
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roast.time
     *
     * @return the value of roast.time
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roast.time
     *
     * @param time the value for roast.time
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}