package com.cdut.myschool.persist.entity;

import java.util.Date;

public class Zone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.user_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.date_time
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private Date dateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.location
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.mind
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String mind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.context
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone.pic_url
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    private String picUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.id
     *
     * @return the value of zone.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.id
     *
     * @param id the value for zone.id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.user_id
     *
     * @return the value of zone.user_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.user_id
     *
     * @param userId the value for zone.user_id
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.date_time
     *
     * @return the value of zone.date_time
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.date_time
     *
     * @param dateTime the value for zone.date_time
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.location
     *
     * @return the value of zone.location
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.location
     *
     * @param location the value for zone.location
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.mind
     *
     * @return the value of zone.mind
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getMind() {
        return mind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.mind
     *
     * @param mind the value for zone.mind
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setMind(String mind) {
        this.mind = mind == null ? null : mind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.context
     *
     * @return the value of zone.context
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.context
     *
     * @param context the value for zone.context
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone.pic_url
     *
     * @return the value of zone.pic_url
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone.pic_url
     *
     * @param picUrl the value for zone.pic_url
     *
     * @mbg.generated Tue Apr 24 15:45:37 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }
}