package com.cdut.myschool.persist.mapper;

import com.cdut.myschool.persist.entity.Complan;
import com.cdut.myschool.persist.entity.ComplanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    long countByExample(ComplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int deleteByExample(ComplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int insert(Complan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int insertSelective(Complan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    List<Complan> selectByExample(ComplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    Complan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Complan record, @Param("example") ComplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int updateByExample(@Param("record") Complan record, @Param("example") ComplanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int updateByPrimaryKeySelective(Complan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complan
     *
     * @mbg.generated Mon May 07 17:08:12 CST 2018
     */
    int updateByPrimaryKey(Complan record);
}