package com.cdut.myschool.persist.mapper;

import com.cdut.myschool.persist.entity.LearnInfo;
import com.cdut.myschool.persist.entity.LearnInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LearnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    long countByExample(LearnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int deleteByExample(LearnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int insert(LearnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int insertSelective(LearnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    List<LearnInfo> selectByExample(LearnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    LearnInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") LearnInfo record, @Param("example") LearnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByExample(@Param("record") LearnInfo record, @Param("example") LearnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByPrimaryKeySelective(LearnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_info
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByPrimaryKey(LearnInfo record);
}