package com.cdut.myschool.persist.mapper;

import com.cdut.myschool.persist.entity.Study;
import com.cdut.myschool.persist.entity.StudyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    long countByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int deleteByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int insert(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int insertSelective(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    List<Study> selectByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    Study selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByExample(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByPrimaryKeySelective(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study
     *
     * @mbg.generated Wed Apr 25 10:38:14 CST 2018
     */
    int updateByPrimaryKey(Study record);
}