package com.cdut.myschool.persist.mapper;

import com.cdut.myschool.persist.entity.Tip;
import com.cdut.myschool.persist.entity.TipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    long countByExample(TipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int deleteByExample(TipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int insert(Tip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int insertSelective(Tip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    List<Tip> selectByExample(TipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    Tip selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") Tip record, @Param("example") TipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int updateByExample(@Param("record") Tip record, @Param("example") TipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int updateByPrimaryKeySelective(Tip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tip
     *
     * @mbg.generated Fri May 25 11:34:31 CST 2018
     */
    int updateByPrimaryKey(Tip record);
}