package com.cdut.myschool.persist.mapper;

import com.cdut.myschool.persist.entity.UserAction;
import com.cdut.myschool.persist.entity.UserActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    long countByExample(UserActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int deleteByExample(UserActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int insert(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int insertSelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    List<UserAction> selectByExample(UserActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    UserAction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserAction record, @Param("example") UserActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int updateByExample(@Param("record") UserAction record, @Param("example") UserActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    int updateByPrimaryKey(UserAction record);
}