package com.cdut.myschool.core.dto;

import java.util.Date;

public class ComplanDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.target_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.context
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.result
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complan.deal_time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Date dealTime;

    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.id
     *
     * @return the value of complan.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.id
     *
     * @param id the value for complan.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.user_id
     *
     * @return the value of complan.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.user_id
     *
     * @param userId the value for complan.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.target_id
     *
     * @return the value of complan.target_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.target_id
     *
     * @param targetId the value for complan.target_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId == null ? null : targetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.context
     *
     * @return the value of complan.context
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.context
     *
     * @param context the value for complan.context
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.result
     *
     * @return the value of complan.result
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.result
     *
     * @param result the value for complan.result
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.time
     *
     * @return the value of complan.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.time
     *
     * @param time the value for complan.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complan.deal_time
     *
     * @return the value of complan.deal_time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complan.deal_time
     *
     * @param dealTime the value for complan.deal_time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }
}