package com.cdut.myschool.core.dto;

import java.util.Date;

public class ReplayDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replay.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replay.tip_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String tipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replay.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replay.content
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replay.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Date time;

    private String userName;

    public String getUserName() {
        return userName;
    }

    public ReplayDto(String tipId, String userId, String content, Date time) {
        this.tipId = tipId;
        this.userId = userId;
        this.content = content;
        this.time = time;
    }

    public ReplayDto() {
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replay.id
     *
     * @return the value of replay.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replay.id
     *
     * @param id the value for replay.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replay.tip_id
     *
     * @return the value of replay.tip_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getTipId() {
        return tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replay.tip_id
     *
     * @param tipId the value for replay.tip_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setTipId(String tipId) {
        this.tipId = tipId == null ? null : tipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replay.user_id
     *
     * @return the value of replay.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replay.user_id
     *
     * @param userId the value for replay.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replay.content
     *
     * @return the value of replay.content
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replay.content
     *
     * @param content the value for replay.content
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replay.time
     *
     * @return the value of replay.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replay.time
     *
     * @param time the value for replay.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}