package com.cdut.myschool.core.dto;

import java.util.Date;
import java.util.List;

public class TipDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.name
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.location
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.look_num
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Integer lookNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.pic_url
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tip.good_num
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Integer goodNum;

    private String userName;

    private List<GoodsDto> goodsId;

    public List<GoodsDto> getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(List<GoodsDto> goodsId) {
        this.goodsId = goodsId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.id
     *
     * @return the value of tip.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.id
     *
     * @param id the value for tip.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.user_id
     *
     * @return the value of tip.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.user_id
     *
     * @param userId the value for tip.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.time
     *
     * @return the value of tip.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.time
     *
     * @param time the value for tip.time
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.name
     *
     * @return the value of tip.name
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.name
     *
     * @param name the value for tip.name
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.location
     *
     * @return the value of tip.location
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.location
     *
     * @param location the value for tip.location
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.look_num
     *
     * @return the value of tip.look_num
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Integer getLookNum() {
        return lookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.look_num
     *
     * @param lookNum the value for tip.look_num
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setLookNum(Integer lookNum) {
        this.lookNum = lookNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.pic_url
     *
     * @return the value of tip.pic_url
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.pic_url
     *
     * @param picUrl the value for tip.pic_url
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tip.good_num
     *
     * @return the value of tip.good_num
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Integer getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tip.good_num
     *
     * @param goodNum the value for tip.good_num
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setGoodNum(Integer goodNum) {
        this.goodNum = goodNum;
    }
}