package com.cdut.myschool.core.dto;

public class UserActionDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_action.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_action.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_action.type
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Integer type;

    private TipDto tip;

    public TipDto getTip() {
        return tip;
    }

    public void setTip(TipDto tip) {
        this.tip = tip;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_action.tip_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String tipId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_action.id
     *
     * @return the value of user_action.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_action.id
     *
     * @param id the value for user_action.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_action.user_id
     *
     * @return the value of user_action.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_action.user_id
     *
     * @param userId the value for user_action.user_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_action.type
     *
     * @return the value of user_action.type
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_action.type
     *
     * @param type the value for user_action.type
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_action.tip_id
     *
     * @return the value of user_action.tip_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getTipId() {
        return tipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_action.tip_id
     *
     * @param tipId the value for user_action.tip_id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setTipId(String tipId) {
        this.tipId = tipId == null ? null : tipId.trim();
    }
}