package com.cdut.myschool.core.dto;

public class UserInfoDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.head_pic_url
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String headPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.coin
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Integer coin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_number
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.location
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.introduce
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.credit_nun
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    private Integer creditNun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.head_pic_url
     *
     * @return the value of user_info.head_pic_url
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getHeadPicUrl() {
        return headPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.head_pic_url
     *
     * @param headPicUrl the value for user_info.head_pic_url
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setHeadPicUrl(String headPicUrl) {
        this.headPicUrl = headPicUrl == null ? null : headPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.coin
     *
     * @return the value of user_info.coin
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.coin
     *
     * @param coin the value for user_info.coin
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_number
     *
     * @return the value of user_info.phone_number
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_number
     *
     * @param phoneNumber the value for user_info.phone_number
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.location
     *
     * @return the value of user_info.location
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.location
     *
     * @param location the value for user_info.location
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.introduce
     *
     * @return the value of user_info.introduce
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.introduce
     *
     * @param introduce the value for user_info.introduce
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.credit_nun
     *
     * @return the value of user_info.credit_nun
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public Integer getCreditNun() {
        return creditNun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.credit_nun
     *
     * @param creditNun the value for user_info.credit_nun
     *
     * @mbg.generated Mon May 07 15:12:54 CST 2018
     */
    public void setCreditNun(Integer creditNun) {
        this.creditNun = creditNun;
    }
}